version: "3.8"
name: vehicle_1811
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehicle_1811
    container_name: vehicle_1811_dev_${USER}
    privileged: true
    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: "host"
    volumes:
      - type: bind
        source: $PWD
        target: /vehicle_1811
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${HOME}/.Xauthority
        target: /root/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/vehicle_1811/config/fastdds_cable.xml

  obc:
    extends: dev
    container_name: vehicle_1811_obc